### ISSUE TITLE
zirconium pants not craftable, but recipe exists.

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#1]
the item is not found in the player inventory with cheats on.
![image](https://github.com/user-attachments/assets/240feb62-1751-4ea0-8e8c-bcbdcc1f3b2b)
even the name of the item is gray in FNEI.
![image](https://github.com/user-attachments/assets/eb43c16d-f44e-4599-8cc8-c3bdb9189b01)
solution: we can make a recipe enable the item, or do something else.
we can add zirconium pants to the recipe `pm-zirconium-processing` at line between 3309 - 3353 in technologies.lua
or enable zirconium pants in prototype\item.lua at line 683 - 691 idk how these works lol sorry

**Comment by TheFrenchTechMan** [comment]
erm what the sigma

**Comment by RemiHinanawi** [comment]
okay nevermind, i think there is a mod setting that enables this lol
