### ISSUE TITLE
Minor spelling mistake at english locale file at line 107

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#10]
`pm-basic-intergrated-circuit-mold=Basic integrated circuit mold`
**intergrated.**
it should've been integrated. there is an extra R between inte- and -grated.
i guess thate explains why we have a duplicate key at line 260.
solution: we can rename the thing at line 107 and remove line 260 i guess.
and we might need to rearrange these keys because oh my god they are so random lol

**Comment by TheFrenchTechMan** [comment]
![image](https://github.com/user-attachments/assets/5787718f-de3a-48e2-98f1-6c58b462dd43)

**Comment by MrSmoothieHuman1** [comment]
this is why you dont code while tired, fixed
