### ISSUE TITLE
Zirconium item does not exist

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#2]
In the english locale file at line 66 we have
`pm-zirconium=Zirconium`
![image](https://github.com/user-attachments/assets/e35021f3-4b52-4fa3-84f2-e22e5c7b9068)
the item does not exist in the game
![image](https://github.com/user-attachments/assets/c595f0ef-6e21-402a-972f-5bf3e44218d1)
nor does its recipe
![image](https://github.com/user-attachments/assets/08bbf593-672b-4fd4-b333-28d007c7ed2c)
solution:
we can either remove the zirconium name from locale.cfg file, or add zirconium item. idk

**Comment by MrSmoothieHuman1** [comment]
Fixed
