### ISSUE TITLE
sodium hydroxide recipe is in post transitional metal tab

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#29]
![image](https://github.com/user-attachments/assets/ac424143-372b-4a79-99dd-b90ab4bd8267)
solution: to move the recipe into alkali metal area maybe

**Comment by RemiHinanawi** [comment]
there is also another sodium hydroxide recipe there, three items to the right

**Comment by RemiHinanawi** [comment]
along with proton beam. down the row

**Comment by RemiHinanawi** [comment]
coolant is also here. its made out of ethylene glycol and nitrogen :sob: i get that its from the same recipe that opens every post transition metal but still

**Comment by RemiHinanawi** [comment]
plus it feels really weird to see polonium fuel cell in p-tm area.. uranium fuel cell is in intermediate products tab...
![image](https://github.com/user-attachments/assets/e8111ea7-82d4-44eb-97b1-59c96e40964e)

**Comment by MrSmoothieHuman1** [comment]
i've decided to put any very, very closely related recipes/items in the elements processing row, mostly to save on space in the intermediates tab - or any prerequisite ingredient that is needed for an elements production (e.g sodium hydroxide), since it is how you unlock it and what you use it for
