### ISSUE TITLE
Processing integrated circuit pressing recipe gives advanced integrated circuit mold instead of processing integrated circuit mold

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#3]
![image](https://github.com/user-attachments/assets/f0302e27-a224-475b-a5f5-36fd9c488e33)
solution: we can change prototype\recipes\altrecipes.lua at line 593 and 594
`{"pm-advanced-integrated-circuit-mold", 3},`
`{name = "pm-advanced-integrated-circuits", amount_min = 2, amount_max = 3}`
these should probably be pm-processing-integrated-circuit and molds... i think.

**Comment by MrSmoothieHuman1** [comment]
oooh shit, i thought i fixed this - fixing it now, it'll probably be put in the next patch
