### ISSUE TITLE
Charger 1's and 2's overlap graphically

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#31]
![image](https://github.com/user-attachments/assets/3cf2820c-6d06-42ef-a586-a5b0b4b6ab37)
charger 1 overlaps with 1
charger 1 overlaps with 2
charger 2 overlaps with 2

**Comment by RemiHinanawi** [comment]
molten and colden inators do too
![image](https://github.com/user-attachments/assets/8983b4df-1678-4efb-bb1f-c2389b901268)

**Comment by MrSmoothieHuman1** [comment]
minor graphical issue, i'll see if i can do anything about it
