### ISSUE TITLE
Advanced breadboard mold item is named as "basic breadboard mold"

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#4]
![image](https://github.com/user-attachments/assets/e2303acf-23f4-46de-9445-73b36c6988eb)
at line 112 of english locale.cfg file
solution: we can just change it to "Advanced breadboard mold"

**Comment by MrSmoothieHuman1** [comment]
Already fixed in the next update :]

**Comment by RemiHinanawi** [comment]
alrighty then
