### ISSUE TITLE
Cadmium items are incorrectly named "cadnium"

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#5]
![image](https://github.com/user-attachments/assets/14e3e6a2-af2f-4000-89d0-6b52aa6970e7)
solution: change english locale.cfg file at lines 19, 236, 431 from "cadnium" to "cadmium". this change will not require putting a migration.
also, in the same file at lines 253, 726, 875, 1030 the cadmium is spelled correctly, however the internal name for them is still "cadnium". we might need to create a migration for all 7 instances of cadniums.

**Comment by MrSmoothieHuman1** [comment]
im fine with the code names being spelt wrong as long as isnt major, because no-one is gonna see it and it *shouldnt* become an issue, but i have fixed the locale names
