### ISSUE TITLE
Compatibility issue with squeak through 2

### ISSUE THREAD

**Issue by dirkschut** [MrSmoothieHuman1/periodic-madness#50]
Loading PM and ST2 causes a crash on startup:

![image](https://github.com/user-attachments/assets/76c7a34a-48c2-4f86-844f-b4a1477c38a3)

[mod-list.json](https://github.com/user-attachments/files/17968726/mod-list.json)

See attached file for modlist for testing

**Comment by MrSmoothieHuman1** [comment]
fixed! easiest one i've ever had to deal with, will upload fix to the mod portal soon
