### ISSUE TITLE
Compatibility issue with Intermodal Containers

### ISSUE THREAD

**Issue by dirkschut** [MrSmoothieHuman1/periodic-madness#51]
Crash on startup with both PM and Intermodal Containers

![image](https://github.com/user-attachments/assets/566f8270-1fd7-49ae-a268-b1cc06dfe061)

[mod-list.json](https://github.com/user-attachments/files/17968799/mod-list.json)

**Comment by MrSmoothieHuman1** [comment]
all fixed, damn myself for not giving unused stuff subgroups!!
