### ISSUE TITLE
Empty item category/tab slot

### ISSUE THREAD

**Issue by dirkschut** [MrSmoothieHuman1/periodic-madness#52]
![image](https://github.com/user-attachments/assets/1ec79f35-7a11-4d2e-b292-d02449bca857)
There is an empty slot where an item category/tab should be...

**Comment by MrSmoothieHuman1** [comment]
this is an issue with the way that categories and tabs are formed, and i cannot do anything about it unfortnately (or nothing i can find) - its annoying, but i decided to change how long the subgroup rows are and this is a byproduct of that :[
