### ISSUE TITLE
"Filled plastic science mold" used twice in locale file

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#8]
in english locale config file at line 207 and 210, "Filled plastic science mold" is used twice, one for key `pm-filled-plastic-mold` and the other for key `pm-filled-plastic-science-mold`.
Also, prototype has internal name `pm-plastic-science-mold-filling` is it just me or is this different from the key name in the locale file? i couldn't find this name in the locale.
![image](https://github.com/user-attachments/assets/1f1d32dc-7bef-4a58-92a9-ae586e171b58)
solution: might want to remove `pm-filled-plastic-mold=Filled plastic science mold` at line 207. it doesn't do anything as far as i can see. also, prototype name and locale key name is different.. is it even possible? lol.
![image](https://github.com/user-attachments/assets/452a9a3d-35ae-4a97-ba0d-ccc9b0008650)
but no... it has `pm-filled-plastic-science-mold` as prototype name in lua file.
I guess factorio is drunk?

**Comment by MrSmoothieHuman1** [comment]
Fixed
