### ISSUE TITLE
pm-stainless-steel item does not exist

### ISSUE THREAD

**Issue by RemiHinanawi** [MrSmoothieHuman1/periodic-madness#9]
...yet it exists at the english locale file.
`pm-stainless-steel=Stainless steel`
at line 40
solution: the game already uses the stainless steel localization name at line 229 as "stainless steel alloy" for some reason, so we can delete this i think

**Comment by TheFrenchTechMan** [comment]
this one you can remove, I removed it from the FR locale and the EN too iirc.
